NAVBAR ADDED
MAARK-2-0/Wix-clone pull request #5
Opened 2020-05-14 13:16 UTC by RohithChittibommala

I ADDED NAVBAR HOWEVER THERE ARE SOME BUGS I NEED SOME GUIDANCE REGARDING THIS

2020-05-16 15:40 UTC, pAditya198 commented
@anujpuri72 don't merge the PR squash and merge it.

2020-05-16 16:36 UTC, pAditya198 commented
@RohithChittibommala  add screenshots of the updates

2020-05-16 16:38 UTC, pAditya198 commented on client/src/Components/App.js
> +    return <Home />;
Why did you removed the route? Change it back

2020-05-16 16:42 UTC, pAditya198 commented on client/src/Components/CusButton.jsx
> +    const value = currentTarget.value;
Is there really a requirement to add two constants to set state?

2020-05-16 16:43 UTC, pAditya198 commented on client/src/Components/CusButton.jsx
> +    console.log("get Input styles" + color);
remove console.log()

2020-05-16 16:46 UTC, pAditya198 commented on client/src/Components/CusButton.jsx
> +    styles.backgroundColor = `${color}`;
you are not reusing the object styles again so avoid creating a const and simply 
return {
objectData
}

2020-05-16 16:49 UTC, pAditya198 commented on client/src/Components/CusButton.jsx
> +        />
Why did you add input field inside a button?

2020-05-16 16:50 UTC, pAditya198 commented on client/src/Components/Home/DarkNavBar.jsx
> +// import "../../scss/components/_navbar.scss";
remove comment if not necessary

2020-05-16 16:50 UTC, pAditya198 commented on client/src/Components/Home/DarkNavBar.jsx
> +console.log("hell");
remove console.log()

2020-05-16 16:51 UTC, pAditya198 commented on client/src/Components/Home/DarkNavBar.jsx
> +    const backgroundColor = this.props.styles.backgroundColor;
was the variable necessary

2020-05-16 16:52 UTC, pAditya198 commented on client/src/Components/Home/DarkNavBar.jsx
> +    console.log(label);
remove log

2020-05-16 16:53 UTC, pAditya198 commented on client/src/Components/Home/DarkNavBar.jsx
> +    console.log("get " + element.height);
remove log

2020-05-16 16:53 UTC, pAditya198 commented on client/src/Components/Home/DarkNavBar.jsx
> +  // };
remove comments

2020-05-16 16:54 UTC, pAditya198 commented on client/src/Components/Home/DarkNavBar.jsx
> +      </React.Fragment>
There is no need of React Fragment here.

2020-05-16 16:59 UTC, pAditya198 commented on client/src/Components/Home/NavBaar.jsx
> +            console.log(element);
remove log

2020-05-16 17:00 UTC, pAditya198 commented on client/src/Components/Home/NavBaar.jsx
> +    console.log(elements);
remove log

2020-05-16 17:00 UTC, pAditya198 commented on client/src/Components/Home/NavBaar.jsx
> +    console.log("hello");
remove log

2020-05-16 17:04 UTC, pAditya198 requested changes

2020-05-16 17:04 UTC, pAditya198 commented on client/src/Components/Home/NavBaar.jsx
> +    // console.log(card.style.top, card.style.top);
remove comment

2020-05-16 17:04 UTC, pAditya198 commented on client/src/Components/Home/NavBaar.jsx
> +    console.log(navbar_id);
remove log

2020-05-16 17:04 UTC, pAditya198 commented on client/src/Components/Home/NavBaar.jsx
> +    console.log("render Navbar");
remove log

2020-05-16 17:04 UTC, pAditya198 commented on client/src/scss/components/_aside.scss
> +// }
remove comment

2020-05-16 17:04 UTC, pAditya198 commented on client/src/scss/components/_aside.scss
> +// @import url("https://fonts.googleapis.com/css2?family=Didact+Gothic&display=swap");
remove comment

2020-05-16 17:04 UTC, pAditya198 commented on client/src/scss/components/_navbar.scss
> +// }
remove comment

2020-05-18 13:28 UTC, anujpuri72 commented
@RohithChittibommala did u broke side menu functionality on right clicking the element???

2020-05-18 13:35 UTC, anujpuri72 requested changes
U removed on the onContext menu and toggle menu  methods from all the components . check the 'Dropdown'  pr for the implementation

2020-05-19 16:33 UTC, pAditya198 commented
@anujpuri72 everything seems fine squash and this PR

2020-05-19 18:46 UTC, merged